### ISSUE TITLE
Rename fields called `name` to be more descriptive.

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#207]
rename: 

- [x] Telescopes.name -> Telescopes.telescope (#358)
- [x] Instruments.name -> Instrument.instrument (#358)
- [x] Modes.name -> Modes.mode (#358)
- [x] Publications.name -> Publications.publication (#351)

**Comment by kelle** [comment]
Consider using ObsCore column names. 
Telescopes.name -> Telescopes.facility_name
Instruments.name -> Instruments.instrument_name

**Comment by kelle** [comment]
also, Right now, we use lots of acronyms for telescope names. would be nice to have a field where we could spell out telescope name and give more info. E.g., description for the WHT could be "William Hershel Telescope, La Palma" or whatever.

Add description to Instrument and Telescope tables.

**Comment by kelle** [comment]
(Dedicated issue to discuss ObsCore in #353.)

**Comment by kelle** [comment]
From #353:

**Comment by kelle** [comment]
I decided to stick with `telescope` and `instrument`.
